apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-batch-inference
spec:
  shutdownAfterJobFinishes: false
  entrypoint: python code/quickstart_with_Ray_AIR.py
  runtimeEnvYAML: |
    pip:
      - "ray[data,train,xgboost]==2.52.0"
      - xgboost
      - pandas
      - pyarrow
    working_dir: "https://github.com/nkmr-ryo/k8s-ray-on-raspberrypi-cluster/archive/refs/heads/main.zip"
    env_vars:
      NUM_WORKERS: "1"
      CPUS_PER_WORKER: "2"

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.52.0'
    headGroupSpec:
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.52.0
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265 # Ray dashboard
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "1"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "4Gi"
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.52.0
            resources:
              limits:
                cpu: "2"
                memory: "3Gi"
              requests:
                cpu: "2"
                memory: "3Gi"
